CREATE TABLE dmInclude(
ownedby varchar(250) NULL DEFAULT NULL ,
lastupdatedby varchar(250) NOT NULL DEFAULT '' ,
teaser longtext NULL ,
label varchar(250) NULL DEFAULT NULL ,
webskinTypename varchar(250) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL DEFAULT '2214-08-20 04:47:04' ,
status varchar(250) NOT NULL DEFAULT 'draft' ,
include varchar(250) NULL DEFAULT NULL ,
displayMethod varchar(250) NULL DEFAULT NULL ,
createdby varchar(250) NOT NULL DEFAULT '' ,
webskin varchar(250) NULL DEFAULT NULL ,
teaserImage varchar(50) NULL DEFAULT NULL ,
datetimecreated datetime NOT NULL DEFAULT '2214-08-20 04:47:04' ,
lockedBy varchar(250) NULL DEFAULT NULL ,
catInclude varchar(250) NULL DEFAULT NULL ,
locked tinyint(1) NOT NULL DEFAULT 0 ,
ObjectID varchar(50) NOT NULL DEFAULT '' ,
title varchar(250) NULL DEFAULT NULL 
);
