CREATE TABLE dmNavigation(
ownedby nvarchar(250) NULL DEFAULT NULL ,
lastupdatedby nvarchar(250) NOT NULL DEFAULT '' ,
internalRedirectID nvarchar(50) NULL DEFAULT NULL ,
label nvarchar(250) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL ,
externalRedirectURL nvarchar(250) NULL DEFAULT NULL ,
ExternalLink nvarchar(50) NULL DEFAULT NULL ,
status nvarchar(250) NOT NULL DEFAULT 'draft' ,
lNavIDAlias nvarchar(250) NULL DEFAULT NULL ,
fu nvarchar(250) NULL DEFAULT NULL ,
navType nvarchar(250) NOT NULL DEFAULT 'aObjectIDs' ,
createdby nvarchar(250) NOT NULL DEFAULT '' ,
target nvarchar(250) NULL DEFAULT NULL ,
datetimecreated datetime NOT NULL ,
lockedBy nvarchar(250) NULL DEFAULT NULL ,
options nvarchar(250) NULL DEFAULT NULL ,
locked bit NOT NULL DEFAULT 0 ,
ObjectID nvarchar(50) NOT NULL DEFAULT '' ,
title nvarchar(250) NULL DEFAULT NULL 
);
