CREATE TABLE farWebfeed(
subtitle varchar(250) NULL DEFAULT NULL ,
catFilter longtext NULL ,
itunessubtitleproperty varchar(250) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL ,
copyright varchar(250) NULL DEFAULT NULL ,
itunescategories varchar(250) NULL DEFAULT NULL ,
editoremail varchar(250) NULL DEFAULT NULL ,
createdby varchar(250) NOT NULL DEFAULT '' ,
bAuthor tinyint(1) NULL DEFAULT 0 ,
dateproperty varchar(250) NULL DEFAULT 'datetimecreated' ,
url varchar(250) NULL DEFAULT NULL ,
titleproperty varchar(250) NULL DEFAULT 'title' ,
ObjectID varchar(50) NOT NULL DEFAULT '' ,
generator varchar(250) NULL DEFAULT 'http://www.farcrycms.org/' ,
ownedby varchar(250) NULL DEFAULT NULL ,
contentproperty varchar(250) NULL DEFAULT 'teaser' ,
editor varchar(250) NULL DEFAULT NULL ,
lastupdatedby varchar(250) NOT NULL DEFAULT '' ,
language varchar(250) NULL DEFAULT NULL ,
description varchar(250) NULL DEFAULT NULL ,
itunesimage varchar(250) NULL DEFAULT NULL ,
itunesdurationproperty varchar(250) NULL DEFAULT NULL ,
enclosurefileproperty varchar(250) NULL DEFAULT NULL ,
label varchar(250) NULL DEFAULT NULL ,
itunesauthor varchar(250) NULL DEFAULT NULL ,
keywords varchar(250) NULL DEFAULT NULL ,
atomicon varchar(250) NULL DEFAULT NULL ,
directory varchar(250) NULL DEFAULT NULL ,
iTunesFeedId decimal(11,0) NULL ,
skiphours varchar(250) NULL DEFAULT NULL ,
datetimecreated datetime NOT NULL ,
lockedBy varchar(250) NULL DEFAULT NULL ,
feedimage varchar(250) NULL DEFAULT NULL ,
skipdays varchar(250) NULL DEFAULT NULL ,
locked tinyint(1) NOT NULL DEFAULT 0 ,
keywordsproperty varchar(250) NULL DEFAULT NULL ,
itemtype varchar(250) NULL DEFAULT NULL ,
title varchar(250) NULL DEFAULT NULL 
);
