CREATE TABLE dmInclude(
ownedby nvarchar(250) NULL DEFAULT NULL ,
lastupdatedby nvarchar(250) NOT NULL DEFAULT '' ,
teaser ntext NULL ,
label nvarchar(250) NULL DEFAULT NULL ,
webskinTypename nvarchar(250) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL ,
status nvarchar(250) NOT NULL DEFAULT 'draft' ,
include nvarchar(250) NULL DEFAULT NULL ,
displayMethod nvarchar(250) NULL DEFAULT NULL ,
createdby nvarchar(250) NOT NULL DEFAULT '' ,
webskin nvarchar(250) NULL DEFAULT NULL ,
teaserImage nvarchar(50) NULL DEFAULT NULL ,
datetimecreated datetime NOT NULL ,
lockedBy nvarchar(250) NULL DEFAULT NULL ,
catInclude nvarchar(250) NULL DEFAULT NULL ,
locked bit NOT NULL DEFAULT 0 ,
ObjectID nvarchar(50) NOT NULL DEFAULT '' ,
title nvarchar(250) NULL DEFAULT NULL 
);
