CREATE TABLE farWorkflow(
ownedby nvarchar(250) NULL DEFAULT NULL ,
lastupdatedby nvarchar(250) NOT NULL DEFAULT '' ,
description ntext NULL ,
label nvarchar(250) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL ,
bTasksComplete bit NULL DEFAULT 0 ,
workflowDefID nvarchar(50) NULL DEFAULT NULL ,
createdby nvarchar(250) NOT NULL DEFAULT '' ,
completionDate datetime NULL DEFAULT NULL ,
datetimecreated datetime NOT NULL ,
bActive bit NULL DEFAULT 1 ,
bWorkflowComplete bit NULL DEFAULT 0 ,
lockedBy nvarchar(250) NULL DEFAULT NULL ,
bWorkflowSetupComplete bit NULL DEFAULT 0 ,
referenceID nvarchar(50) NULL DEFAULT NULL ,
locked bit NOT NULL DEFAULT 0 ,
ObjectID nvarchar(50) NOT NULL DEFAULT '' ,
title nvarchar(250) NULL DEFAULT NULL 
);
