CREATE TABLE dmHTML(
ownedby varchar(250) NULL DEFAULT NULL ,
lastupdatedby varchar(250) NOT NULL DEFAULT '' ,
Teaser longtext NULL ,
label varchar(250) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL ,
status varchar(250) NOT NULL DEFAULT 'draft' ,
reviewDate datetime NULL DEFAULT NULL ,
displayMethod varchar(250) NOT NULL DEFAULT 'displayPageStandard' ,
createdby varchar(250) NOT NULL DEFAULT '' ,
teaserImage varchar(50) NULL DEFAULT NULL ,
Body longtext NULL ,
datetimecreated datetime NOT NULL ,
seoTitle varchar(250) NULL DEFAULT NULL ,
lockedBy varchar(250) NULL DEFAULT NULL ,
versionID varchar(50) NULL DEFAULT NULL ,
catHTML varchar(250) NULL DEFAULT NULL ,
metaKeywords longtext NULL ,
extendedmetadata longtext NULL ,
locked tinyint(1) NOT NULL DEFAULT 0 ,
Title varchar(250) NULL DEFAULT NULL ,
ObjectID varchar(50) NOT NULL DEFAULT '' 
);
