CREATE TABLE dmNavigation(
ownedby varchar(250) NULL DEFAULT NULL ,
lastupdatedby varchar(250) NOT NULL DEFAULT '' ,
internalRedirectID varchar(50) NULL DEFAULT NULL ,
label varchar(250) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL ,
externalRedirectURL varchar(250) NULL DEFAULT NULL ,
ExternalLink varchar(50) NULL DEFAULT NULL ,
status varchar(250) NOT NULL DEFAULT 'draft' ,
lNavIDAlias varchar(250) NULL DEFAULT NULL ,
fu varchar(250) NULL DEFAULT NULL ,
navType varchar(250) NOT NULL DEFAULT 'aObjectIDs' ,
createdby varchar(250) NOT NULL DEFAULT '' ,
target varchar(250) NULL DEFAULT NULL ,
datetimecreated datetime NOT NULL ,
lockedBy varchar(250) NULL DEFAULT NULL ,
options varchar(250) NULL DEFAULT NULL ,
locked tinyint(1) NOT NULL DEFAULT 0 ,
ObjectID varchar(50) NOT NULL DEFAULT '' ,
title varchar(250) NULL DEFAULT NULL 
);
